# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TransparentNavigationDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for TransparentNavigationDemo
  pod 'TransparentNavigation'

  target 'TransparentNavigationDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TransparentNavigationDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
